import numpy as np
a = np.zeros((10, 2))
a = np.arange(6).reshape((3, 2))
print ("a array 3x2")
print (a.ndim)
print (a.size)
print (a.shape)
np.reshape(a, (2, 3))
print ("a array 2x3")
print (a.ndim)
print (a.size)
print (a.shape)
np.reshape(np.ravel(a), (2, 3))
print ("a array 2x3 ravelled")
print (a.ndim)
print (a.size)
print (a.shape)
np.reshape(a, (2, 3), order='F')
print ("a array 2x3 ordered")
print (a.ndim)
print (a.size)
print (a.shape)
np.reshape(np.ravel(a, order='F'), (2, 3), order='F')
print ("a array 2x3 ordered ravelled")
print (a.ndim)
print (a.size)
print (a.shape)
d = np.array([[1,2,3], [4,5,6]])
np.reshape(d, 6)
print ("d reshaped")
print (a.ndim)
print (a.size)
print (a.shape)
np.reshape(d, 6, order='F')
print ("d ordered")
print (a.ndim)
print (a.size)
print (a.shape)
np.reshape(d, (3,-1))
print ("d unspecified")
print (a.ndim)
print (a.size)
print (a.shape)